src/Entity/Diploma.php
<?php

namespace App\Entity;

use App\Repository\DiplomaRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DiplomaRepository::class)
 */
class Diploma
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="date")
     */
    private $year;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\ManyToOne(targetEntity=Nomination::class, inversedBy="diplomas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $nomination;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getYear(): ?\DateTimeInterface
    {
        return $this->year;
    }

    public function setYear(\DateTimeInterface $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getNomination(): ?Nomination
    {
        return $this->nomination;
    }

    public function setNomination(?Nomination $nomination): self
    {
        $this->nomination = $nomination;

        return $this;
    }
}

src/Controller/NominationController.php
<?php

namespace App\Controller;

use App\Entity\AwData;
use App\Entity\Diploma;
use App\Entity\GoalsInfo;
use App\Entity\Job;
use App\Entity\Lang;
use App\Entity\Nomination;
use App\Entity\PersonnalInfos;
use App\Entity\Situation;
use App\Entity\Skill;
use App\Entity\User;
use App\Form\AwDataFormType;
use App\Form\DiplomaCollectionType;
use App\Form\DiplomaFormType;
use App\Form\GoalsInfoFormType;
use App\Form\JobFormType;
use App\Form\JobsCollectionFormType;
use App\Form\LangFormType;
use App\Form\LangsCollectionFormType;
use App\Form\PersonnalInfoFormType;
use App\Form\SituationFormType;
use App\Form\SkillFormType;
use App\Form\SkillsCollectionFormType;
use App\Repository\CourseRepository;
use App\Repository\NominationRepository;
use App\Services\MailService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class NominationController extends AbstractController
{
    /**
     * @Route(path="/nomination/{id}/1", name="nomination_personnal_info")
     */
    public function nominationPersonnalInfos(Request $request, int $id, CourseRepository $crepo, NominationRepository $nrepo): Response
    {

        if ($nrepo->getWaitingNominationNumber($this->getUser()) >= 1){
            $this->addFlash("warning", "Veuillez attendre que votre candidature soit refusée ou validée pour en soumettre une nouvelle.");
            return $this->redirectToRoute("home");
        }
        if (!$this->isGranted("IS_AUTHENTICATED_FULLY")){
            $this->addFlash("warning", "Vous devez être connecté pour déposer votre candidature. Veuillez vous connecter ou créer un compte.");
            return $this->redirectToRoute("login");
        }
        $personnalInfos = new PersonnalInfos();
        $form = $this->createForm(PersonnalInfoFormType::class, $personnalInfos);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $session = $request->getSession();
            $session->set("nomination", [
                "nominationName" => $crepo->findOneById($id)->getName(),
                "personnalInfos" => $personnalInfos
            ]);
            return $this->redirectToRoute("nomination_situation", ["id" => $id]);
        }
        return $this->render('nomination/nominationPersonnalInfos.html.twig', [
            "form" => $form->createView(),
            'stepNumber' => 1
        ]);
    }

    
    /**
     * @Route(path="/nomination/{id}/2", name="nomination_situation")
     */
    public function nominationSituation(Request $request, int $id): Response
    {
        $session= $request->getSession();
        $nominationArray= $session->get("nomination", []);
        if(!key_exists("personnalInfos", $nominationArray)){
            $this->addFlash("warning", "Veuillez suivre le processus de candidature et remplir les étapes une par une");
            return $this->redirectToRoute("nomination_personnal_info", ["id" => $id]);
        }
        $situation = new Situation();
        $form = $this->createForm(SituationFormType::class, $situation);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $nominationArray["situation"] = $situation;
            $session->set("nomination", $nominationArray);
            return $this->redirectToRoute("nomination_diploma", ["id" => $id]);
        }
        return $this->render('nomination/nominationSituation.html.twig', [
            "form" => $form->createView(),
            'stepNumber' => 1
        ]);
    }
    /**
     * @Route(path="/nomination/{id}/3", name="nomination_diploma")
     */
    public function nominationDiplomas(Request $request, int $id): Response
    {
        $session= $request->getSession();
        $nominationArray= $session->get("nomination", []);
        if(!key_exists("situation", $nominationArray)){
            $this->addFlash("warning", "Veuillez suivre le processus de candidature et remplir les étapes une par une");
            return $this->redirectToRoute("nomination_personnal_info", ["id" => $id]);
        }
        if (!isset($nominationArray["diplomas"])){
            $nominationArray["diplomas"] = [];
            $session->set("nomination", $nominationArray);
        }
        $form= $this->createForm(DiplomaCollectionType::class, $nominationArray);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $nominationArray["diplomas"] = $form->get("diplomas")->getData();
            $session->set("nomination", $nominationArray);
            return $this->redirectToRoute("nomination_skills", ["id" => $id]);
        }
        return $this->render('nomination/nominationDiplomas.html.twig', [
            "form" => $form->createView(),
            "id" => $id,
            'stepNumber' => 2
        ]);
    }

    /**
     * @Route(path="/nomination/{id}/4", name="nomination_skills")
     */
    public function nominationSkills(Request $request, int $id): Response
    {
        $session= $request->getSession();
        $nominationArray= $session->get("nomination", []);
        if(!key_exists("diplomas", $nominationArray)){
            $this->addFlash("warning", "Veuillez suivre le processus de candidature et remplir les étapes une par une");
            return $this->redirectToRoute("nomination_personnal_info", ["id" => $id]);
        }
        if (!isset($nominationArray["skills"])){
            $nominationArray["skills"] = [];
            $session->set("nomination", $nominationArray);
        }
        $form= $this->createForm(SkillsCollectionFormType::class, $nominationArray);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $nominationArray["skills"] = $form->get("skills")->getData();
            $session->set("nomination", $nominationArray);
            return $this->redirectToRoute("nomination_lang", ["id" => $id]);
        }
        return $this->render('nomination/nominationSkills.html.twig', [
            "form" => $form->createView(),
            "id" => $id,
            'stepNumber' => 3
        ]);
    }

    /**
     * @Route(path="/nomination/{id}/5", name="nomination_lang")
     */
    public function nominationLangs(Request $request, int $id): Response
    {
        $session= $request->getSession();
        $nominationArray= $session->get("nomination", []);
        if(!key_exists("skills", $nominationArray)){
            $this->addFlash("warning", "Veuillez suivre le processus de candidature et remplir les étapes une par une");
            return $this->redirectToRoute("nomination_personnal_info", ["id" => $id]);
        }
        if (!isset($nominationArray["langs"])){
            $nominationArray["langs"] = [];
            $session->set("nomination", $nominationArray);
        }
        $form= $this->createForm(LangsCollectionFormType::class, $nominationArray);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $nominationArray["langs"] = $form->get("langs")->getData();
            $session->set("nomination", $nominationArray);
            return $this->redirectToRoute("nomination_jobs", ["id" => $id]);
        }
        return $this->render('nomination/nominationLangs.html.twig', [
            "form" => $form->createView(),
            "id" => $id,
            'stepNumber' => 3
        ]);
    }



    /**
     * @Route(path="/nomination/{id}/6", name="nomination_jobs")
     */
    public function nominationJobs(Request $request, int $id): Response
    {
        $session= $request->getSession();
        $nominationArray= $session->get("nomination", []);
        if(!key_exists("langs", $nominationArray)){
            $this->addFlash("warning", "Veuillez suivre le processus de candidature et remplir les étapes une par une");
            return $this->redirectToRoute("nomination_personnal_info", ["id" => $id]);
        }
        if (!isset($nominationArray["jobs"])){
            $nominationArray["jobs"] = [];
            $session->set("nomination", $nominationArray);
        }
        $form= $this->createForm(JobsCollectionFormType::class, $nominationArray);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $nominationArray["jobs"] = $form->get("jobs")->getData();
            $session->set("nomination", $nominationArray);
            return $this->redirectToRoute("nomination_goals_info", ["id" => $id]);
        }
        return $this->render('nomination/nominationJobs.html.twig', [
            "form" => $form->createView(),
            "id" => $id,
            'stepNumber' => 4
        ]);
    }

    /**
     * @Route(path="/nomination/{id}/7", name="nomination_goals_info")
     */
    public function nominationGoalsInfo(Request $request, int $id): Response
    {
        $session= $request->getSession();
        $nominationArray= $session->get("nomination", []);
        if(!key_exists("jobs", $nominationArray)){
            $this->addFlash("warning", "Veuillez suivre le processus de candidature et remplir les étapes une par une");
            return $this->redirectToRoute("nomination_personnal_info", ["id" => $id]);
        }
        $goalsInfo = new GoalsInfo();
        $form = $this->createForm(GoalsInfoFormType::class, $goalsInfo);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $nominationArray["goalsInfo"] = $goalsInfo;
            $session->set("nomination", $nominationArray);
            return $this->redirectToRoute("nomination_aw_data", ["id" => $id]);
        }
        return $this->render('nomination/nominationGoalsInfos.html.twig', [
            "form" => $form->createView(),
            'stepNumber' => 5
        ]);
    }

    /**

templates/nomination/nominationAwData.html.twig
{% extends 'nomination/base/nominationBase.html.twig' %}

{% block content %}
    <h2 class="title-underlined text-dark mb-5">6. Nous</h2>
    {{ form_start(form) }}
    {{ form_row(form.awKnowledge) }}
    {{ form_row(form.otherTrainingFailed) }}
    {{ form_row(form.trainingType) }}
    <div class="d-flex justify-content-center my-5">
		<img src="{{ asset('img/straight_line.png') }}" alt="pointillés" class="d-block d-md-none"/>
		<img src="{{ asset('img/straight_line_2.png') }}" alt="pointillés" class="d-none d-md-block"/>
	</div>
	<div class="d-flex flex-column flex-sm-row justify-content-between gap-2 mt-5 mb-3">
		<button class="button button-outlined" type="reset">Annuler</button>
		<button class="button button-secondary" type="submit">Suivant</button>
	</div>
    {{ form_end(form) }}
{% endblock %}

templates/nomination/nominationDiplomas.html.twig
{% extends 'nomination/base/nominationBase.html.twig' %}

{% block javascripts %}
	{{ parent() }}
	{{ encore_entry_script_tags('nominationCollection') }}
{% endblock %}

{% block content %}
	{{ form_start(form) }}
	<h2 class="title-underlined text-dark mb-5">2. Formation</h2>
	<ul id="collection-field-list" data-prototype="{{ form_widget(form.diplomas.vars.prototype)|e }}" data-index="{{ form.diplomas|length }}" class="p-0 m-0 list-unstyled">
		{% for diploma in form.diplomas %}
			<li class="form-collection-field">
				{{ form_widget(diploma) }}
				<a class="button button-outlined delete-field-link mb-3" role="button">Supprimer</a>
			</li>
		{% endfor %}
	</ul>
	<div class="d-flex justify-content-sm-end">
		<button class="button button-primary mt-3 add-field-button">Ajouter un diplôme</button>
	</div>
	<div class="d-flex justify-content-center my-5">
		<img src="{{ asset('img/straight_line.png') }}" alt="pointillés" class="d-block d-md-none"/>
		<img src="{{ asset('img/straight_line_2.png') }}" alt="pointillés" class="d-none d-md-block"/>
	</div>
	<div class="d-flex flex-column flex-sm-row justify-content-between gap-2 mt-5 mb-3">
		<button class="button button-outlined" type="reset">Annuler</button>
		<button class="button button-secondary" type="submit">Suivant</button>
	</div>
	{{ form_end(form) }}
{% endblock %}

templates/nomination/nominationEigth.html.twig
{% extends 'nomination/base/nominationBase.html.twig' %}

{% block content %}
    <h1>Vos langues</h1>
    <button type="button" class="btn d-flex w-100 align-items-center justify-content-between p-2" data-bs-toggle="modal" data-bs-target="#langModal">Ajouter une langue<i class="fas fa-plus fa-lg"></i></button>
    {% if langs %}
        {% for lang in langs %}
            {{ include('nomination/Components/langCard.html.twig')}}
        {% endfor %}
    {% endif %}
    <button type="button" class="btn w-100"><a href="{{ path('nomination_end', {"slug": slug}) }}">Valider</a></button>
    <div class="modal fade" id="langModal" tabindex="-1" role="dialog" aria-labelledby="ModalDiploma" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">Saississez les informations concernant cette langue</h3>
                </div>
                {{ form_start(form) }}
                <div class="modal-body">
                    {{ form_row(form.title) }}
                    {{ form_row(form.level) }}
                </div>
                <div class="modal-footer d-flex align-items-center justify-content-between">
                    {{ form_widget(form.reset) }}
                    {{ form_widget(form.submit) }}
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/nomination/nominationFifth.html.twig
{% extends 'nomination/base/nominationBase.html.twig' %}

{% block content %}
    <h1>Votre situation actuelle</h1>
    {{ form_start(form) }}
        {{ form_row(form.title) }}
        {{ form_row(form.beginningDate) }}
        <div class="d-flex justify-content-between align-items-center">
            {{ form_widget(form.reset) }}
            {{ form_widget(form.submit) }}
        </div>
    {{ form_end(form) }}
{% endblock %}

templates/nomination/nominationFirst.html.twig
{% extends 'nomination/base/nominationBase.html.twig' %}

{% block content %}
    <h1>Informations vous concernant</h1>
    {{ form_start(form) }}
        {{ form_row(form.birthDate) }}
        {{ form_row(form.birthPlace) }}
        {{ form_row(form.nationalSecNumber) }}
        {{ form_row(form.nationality) }}
        {{ form_row(form.familyState) }}
        {{ form_row(form.drivingLicence) }}
        <div class="d-flex align-items-center justify-content-between">
            {{ form_widget(form.reset) }}
            {{ form_widget(form.submit)}}
        </div>
    {{ form_end(form) }}
{% endblock %}

templates/nomination/nominationFourth.html.twig
{% extends 'nomination/base/nominationBase.html.twig' %}

{% block content %}
    <h1>Votre experience</h1>
    <button type="button" class="btn d-flex w-100 align-items-center justify-content-between p-2" data-bs-toggle="modal" data-bs-target="#diplomaModal">Ajouter une experience<i class="fas fa-plus fa-lg"></i></button>
    {% if jobs %}
        {% for job in jobs %}
            {{ include('nomination/Components/jobCard.html.twig')}}
        {% endfor %}
    {% endif %}
    <button type="button" class="btn w-100"><a href="{{ path('nomination_situation', {"slug": slug}) }}">Valider</a></button>
    <div class="modal fade" id="diplomaModal" tabindex="-1" role="dialog" aria-labelledby="ModalDiploma" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">Saississez les informations concernant cette experience</h3>
                </div>
                {{ form_start(form) }}
                <div class="modal-body">
                    {{ form_row(form.jobTitle) }}
                    {{ form_row(form.beginingDate) }}
                    <div class="d-flex flex-column">
                        {{ form_label(form.stayTime) }}
                        <div class="d-flex gap-3 align-items-center justify-content-between mb-3">
                            {{ form_widget(form.stayTime) }}
                            {{ form_widget(form.stayType) }}
                        </div>
                    </div>
                    {{ form_row(form.companyName) }}
                </div>
                <div class="modal-footer d-flex align-items-center justify-content-between">
                    {{ form_widget(form.reset) }}
                    {{ form_widget(form.submit) }}
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/nomination/nominationJobs.html.twig
{% extends 'nomination/base/nominationBase.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('nominationCollection') }}
{% endblock %}

{% block content %}
    {{ form_start(form) }}
    <h2 class="title-underlined text-dark mb-5">4. Mes expériences</h2>
    <ul id="collection-field-list"
        data-prototype="{{ form_widget(form.jobs.vars.prototype)|e }}"
        data-index="{{ form.jobs|length }}"
        class="p-0 m-0 list-unstyled"
    >
        {% for job in form.jobs %}
            <li class="form-collection-field">
                {{ form_widget(job) }}
                <a class="button button-outlined delete-field-link mb-3" role="button">Supprimer</a>
            </li>
        {% endfor %}
    </ul>
    <div class="d-flex justify-content-sm-end">
		<button class="button button-primary mt-3 add-field-button">Ajouter une expérience</button>
	</div>
	<div class="d-flex justify-content-center my-5">
		<img src="{{ asset('img/straight_line.png') }}" alt="pointillés" class="d-block d-md-none"/>
		<img src="{{ asset('img/straight_line_2.png') }}" alt="pointillés" class="d-none d-md-block"/>
	</div>
	<div class="d-flex flex-column flex-sm-row justify-content-between gap-2 mt-5 mb-3">
		<button class="button button-outlined" type="reset">Annuler</button>
		<button class="button button-secondary" type="submit">Suivant</button>
	</div>
    {{ form_end(form) }}
{% endblock %}

templates/nomination/nominationLangs.html.twig
{% extends 'nomination/base/nominationBase.html.twig' %}

{% block javascripts %}
	{{ parent() }}
	{{ encore_entry_script_tags('nominationCollection') }}
{% endblock %}

{% block content %}
	{{ form_start(form) }}
	<h2 class="title-underlined text-dark mb-5">3. Mes Langues</h2>
	<ul id="collection-field-list" data-prototype="{{ form_widget(form.langs.vars.prototype)|e }}" data-index="{{ form.langs|length }}" class="p-0 m-0 list-unstyled">
		{% for lang in form.langs %}
			<li class="form-collection-field">
				{{ form_widget(lang) }}
				<a class="button button-outlined delete-field-link mb-3" role="button">Supprimer</a>
			</li>
		{% endfor %}
	</ul>
	<div class="d-flex justify-content-sm-end">
		<button class="button button-primary mt-3 add-field-button">Ajouter une Langue</button>
	</div>
	<div class="d-flex justify-content-center my-5">
		<img src="{{ asset('img/straight_line.png') }}" alt="pointillés" class="d-block d-md-none"/>
		<img src="{{ asset('img/straight_line_2.png') }}" alt="pointillés" class="d-none d-md-block"/>
	</div>
	<div class="d-flex flex-column flex-sm-row justify-content-between gap-2 mt-5 mb-3">
		<button class="button button-outlined" type="reset">Annuler</button>
		<button class="button button-secondary" type="submit">Suivant</button>
	</div>
	{{ form_end(form) }}
{% endblock %}

templates/nomination/nominationPersonnalInfos.html.twig
{% extends 'nomination/base/nominationBase.html.twig' %} 
{% block content %}
<h2 class="title-underlined text-dark mb-5">1. Vous</h2>
{{ form_start(form) }}
<div class="d-flex flex-column flex-md-row justify-content-md-between">
  <div class="d-flex flex-column form-subgroup">
    {{ form_row(form.birthDate) }}
    {{ form_row(form.birthPlace) }}
  </div>
  <div class="d-flex flex-column form-subgroup">
    {{ form_row(form.nationalSecNumber) }}
    {{ form_row(form.nationality) }}
  </div>
</div>
<div class="d-flex justify-content-center my-5">
  <img src="{{ asset('img/straight_line.png') }}" alt="pointillés" class="d-block d-md-none"/>
  <img src="{{ asset('img/straight_line_2.png') }}" alt="pointillés" class="d-none d-md-block"/>
</div>
<div class="d-flex flex-column flex-md-row justify-content-md-between">
  <div class="d-flex flex-column form-subgroup">
    {{ form_row(form.familyState) }}
  </div>
  <div class="d-flex flex-column form-subgroup">
    {{ form_row(form.drivingLicence) }}
    <div
      class="d-flex flex-column flex-sm-row justify-content-between gap-2 mt-5 mb-3"
    >
      <button class="button button-outlined" type="reset">Annuler</button>
      <button class="button button-secondary" type="submit">Suivant</button>
    </div>
  </div>
</div>
{{ form_end(form) }}
{% endblock %}

templates/nomination/nominationSecond.html.twig
{% extends 'nomination/base/nominationBase.html.twig' %}

{% block content %}
    <h1>Vos diplômes</h1>
    <button type="button" class="btn d-flex w-100 align-items-center justify-content-between p-2" data-bs-toggle="modal" data-bs-target="#diplomaModal">Ajouter un diplome <i class="fas fa-plus fa-lg"></i></button>
    {% if diplomas %}
        {% for diploma in diplomas %}
            {{ include('nomination/Components/diplomaCard.html.twig')}}
        {% endfor %}
    {% endif %}
    <button type="button" class="btn w-100"><a href="{{ path('nomination_skills', {"slug": slug}) }}">Valider</a></button>
    <div class="modal fade" id="diplomaModal" tabindex="-1" role="dialog" aria-labelledby="ModalDiploma" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">Saississez les informations concernant votre diplôme</h3>
                </div>
                {{ form_start(form) }}
                <div class="modal-body">
                    {{ form_row(form.title) }}
                    {{ form_row(form.year) }}
                    {{ form_row(form.description) }}
                </div>
                <div class="modal-footer d-flex align-items-center justify-content-between">
                    {{ form_widget(form.cancel) }}
                    {{ form_widget(form.submit) }}
{#                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>#}
{#                    <button type="button" class="btn btn-primary">Save changes</button>#}
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/nomination/nominationSeven.html.twig
{% extends 'nomination/base/nominationBase.html.twig' %}

{% block content %}
    <h1>Votre relation avec Apprenti-webeur</h1>
    {{ form_start(form) }}
    {{ form_row(form.awKnowledge) }}
    {{ form_row(form.otherTrainingFailed) }}
    {{ form_row(form.trainingType) }}
    <div class="d-flex justify-content-between align-items-center">
        {{ form_widget(form.reset) }}
        {{ form_widget(form.submit) }}
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/nomination/nominationSituation.html.twig
{% extends 'nomination/base/nominationBase.html.twig' %}

{% block content %}
	<h2 class="title-underlined text-dark mb-5">1. Votre situation actuelle</h2>
	{{ form_start(form) }}
	{{ form_row(form.title) }}
	{{ form_row(form.beginningDate) }}
	<div class="d-flex justify-content-center my-5">
		<img src="{{ asset('img/straight_line.png') }}" alt="pointillés" class="d-block d-md-none"/>
		<img src="{{ asset('img/straight_line_2.png') }}" alt="pointillés" class="d-none d-md-block"/>
	</div>
	<div class="d-flex flex-column flex-sm-row justify-content-between gap-2 mt-5 mb-3">
		<button class="button button-outlined" type="reset" data-dismiss="modal">Annuler</button>
		<button class="button button-secondary" type="submit">Suivant</button>
	</div>
	{{ form_end(form) }}
{% endblock %}

templates/nomination/nominationSkills.html.twig
{% extends 'nomination/base/nominationBase.html.twig' %}

{% block javascripts %}
	{{ parent() }}
	{{ encore_entry_script_tags('nominationCollection') }}
{% endblock %}

{% block content %}
	{{ form_start(form) }}
	<h2 class="title-underlined text-dark mb-5">3. Mes compétences</h2>
	<ul id="collection-field-list" data-prototype="{{ form_widget(form.skills.vars.prototype)|e }}" data-index="{{ form.skills|length }}" class="p-0 m-0 list-unstyled">
		{% for skill in form.skills %}
			<li class="form-collection-field">
				{{ form_widget(skill) }}
				<a class="button button-outlined delete-field-link mb-3" role="button">Supprimer</a>
			</li>
		{% endfor %}
	</ul>
	<div class="d-flex justify-content-sm-end">
		<button class="button button-primary mt-3 add-field-button">Ajouter une compétence</button>
	</div>
	<div class="d-flex justify-content-center my-5">
		<img src="{{ asset('img/straight_line.png') }}" alt="pointillés" class="d-block d-md-none"/>
		<img src="{{ asset('img/straight_line_2.png') }}" alt="pointillés" class="d-none d-md-block"/>
	</div>
	<div class="d-flex flex-column flex-sm-row justify-content-between gap-2 mt-5 mb-3">
		<button class="button button-outlined" type="reset">Annuler</button>
		<button class="button button-secondary" type="submit">Suivant</button>
	</div>
	{{ form_end(form) }}
{% endblock %}

templates/nomination/nominationThird.html.twig
{% extends 'nomination/base/nominationBase.html.twig' %}

{% block content %}
    <h1>Vos competences</h1>
    <button type="button" class="btn d-flex w-100 align-items-center justify-content-between p-2" data-bs-toggle="modal" data-bs-target="#diplomaModal">Ajouter une competence<i class="fas fa-plus fa-lg"></i></button>
    {% if skills %}
        {% for skill in skills %}
            {{ include('nomination/Components/skillCard.html.twig')}}
        {% endfor %}
    {% endif %}
    <button type="button" class="btn w-100"><a href="{{ path('nomination_jobs', {"slug": slug}) }}">Valider</a></button>
    <div class="modal fade" id="diplomaModal" tabindex="-1" role="dialog" aria-labelledby="ModalDiploma" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">Saississez les informations concernant votre compétences</h3>
                </div>
                {{ form_start(form) }}
                <div class="modal-body">
                    {{ form_row(form.title) }}
                    {{ form_row(form.level) }}
                </div>
                <div class="modal-footer d-flex align-items-center justify-content-between">
                    {{ form_widget(form.reset) }}
                    {{ form_widget(form.submit) }}
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}